{{- if .Values.kubernetes.deployment.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-sensor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcagent.commonLabels" . | nindent 4 }}
data:
  # TODO We should get rid of this and imply the ring-fence iff the mode is "KUBERNETES"
  configuration.yaml: |
    com.vcc.plugin.kubernetes:
      enabled: true

    com.vcv.kubernetes:
      leader:
        isRingFenced: true
{{- end }}
