{{- if not (typeIs "[]interface {}" .Values.agent.image.pullSecrets) }}
{{- if .Values.agent.image.name | hasPrefix "containers.vc.io" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: containers-vc-io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcagent.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretContainersVCIo" . }}
{{- end -}}
{{- end -}}
{{- if not .Values.agent.keysSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vcagent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcagent.commonLabels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.templating }}
  key: {{ .Values.agent.key }}
  downloadKey: {{ default "''" .Values.agent.downloadKey }}
{{- else }}
{{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
{{- end }}
{{- if .Values.agent.downloadKey }}
  downloadKey: {{ .Values.agent.downloadKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.agent.tls }}
{{- if and (not .Values.agent.tls.secretName) (and .Values.agent.tls.certificate .Values.agent.tls.key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vcagent.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcagent.commonLabels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.agent.tls.certificate }}
  tls.key: {{ .Values.agent.tls.key }}
{{- end }}
{{- end }}
