{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vcagent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcagent.commonLabels" . | nindent 4 }}
{{- end }}